### ISSUE TITLE
Feature request : trim Vec<String>

### ISSUE THREAD

**Issue by nicolaspernoud** [baoyachi/serde_trim#1]
Hello,
Thanks for you useful crate. It would be nice if it could trim vecs of strings as well !
Best regards.

**Comment by baoyachi** [comment]
I'try

**Comment by baoyachi** [comment]
@nicolaspernoud  Now, published new version with `0.4.0`, support `Vec<String>` trim.

See detail: 
> https://github.com/baoyachi/serde_trim/blob/5c7cd1dc4c9b4fb9d23bf1d8b8f3196ba265f609/lib.rs#L37-L47

Use :
```toml
[dependencies]
serde_trim = "0.4.0"
```

**Comment by nicolaspernoud** [comment]
Very nice, thanks !
